api:
  baseURL: /api
  version: v1

spring:
  application:
    name: task-manager
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:h2:./data/task-manager.db;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=TRUE;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true

server:
  port: 9090
  servlet:
    context-path: /task-manager

logging:
  level:
    org:
      springframework:
        web: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
