INSERT INTO TASK(ID, SUMMARY, DESCRIPTION, PRIORITY, DATE, STATUS)
VALUES(5, 'TASK 1', 'Task with correct data', 'NORMAL', DATEADD(MONTH, 1, CURRENT_TIMESTAMP), 'FINISHED');
INSERT INTO TASK(ID, SUMMARY, DESCRIPTION, PRIORITY, DATE, STATUS)
VALUES(7, 'TASK 2', 'Task with correct data', 'HIGH', DATEADD(MONTH, 3, CURRENT_TIMESTAMP), 'SCHEDULED');
INSERT INTO TASK(ID, SUMMARY, DESCRIPTION, PRIORITY, DATE, STATUS)
VALUES(9, 'TASK 3', 'Task in the past', 'LOW', PARSEDATETIME('1970-03-29 09:00:00', 'yyyy-MM-dd HH:mm:ss'), 'CANCELLED');
INSERT INTO TASK(ID, SUMMARY, DESCRIPTION, PRIORITY, DATE, STATUS)
VALUES(11, 'TASK 4', 'A Task to delete', 'NORMAL', DATEADD(DAY, 5, CURRENT_TIMESTAMP), 'SCHEDULED');
