CREATE SEQUENCE TASK_ID_SEQUENCE START WITH 3451 INCREMENT BY 50;
CREATE TABLE TASK(
    ID BIGINT NOT NULL,
    DATE TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRIORITY VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    SUMMARY VARCHAR(255) NOT NULL
);
ALTER TABLE TASK ADD CONSTRAINT TASK_ID_PK PRIMARY KEY(ID);
